DROP DATABASE IF EXISTS db_tareas;
CREATE DATABASE IF NOT EXISTS db_tareas;
USE db_tareas;

CREATE TABLE IF NOT EXISTS users(
user_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(45) NOT NULL UNIQUE,
password VARCHAR(45) NOT NULL UNIQUE,
tel INT UNIQUE,
mail VARCHAR(45) UNIQUE
);

CREATE TABLE IF NOT EXISTS tareas(
tarea_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
tarea VARCHAR(45),
urgencia BOOLEAN,
nota VARCHAR(150),
fk_categoria_id INT
);

CREATE TABLE IF NOT EXISTS users_tareas(/*deberia ser así pero mejor me aseguro*/
users_tareas_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,/*probablemente esto sobre*/
fk_user_id INTEGER UNSIGNED,
fk_tarea_id INTEGER UNSIGNED,
fk_tarea_categoria_id INTEGER UNSIGNED
);

CREATE TABLE IF NOT EXISTS dias(
dia_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
dia DATE,
hora_inicio DATETIME, /* ASEGURAR QUE SEA DATETIME*/
hora_final DATETIME
);

CREATE TABLE IF NOT EXISTS dias_tareas(
dias_tareas_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
fk_dia_id INTEGER UNSIGNED,
fk_tarea_id INTEGER UNSIGNED
);

CREATE TABLE IF NOT EXISTS categorias(
categoria_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
color VARCHAR(45),
color_code VARCHAR(45)
);


